export const isValidEmail = email => /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(email);
export const isValidPassword = password => /^[a-zA-Z0-9.,!@]{8,30}$/.test(password);
export const isValidUsername = username => /^[a-zA-Z0-9_]{4,20}$/.test(username);
export const isValidName = name => /^[a-zA-Z ]+$/.test(name);
export const isValidInterest = interest => /^[a-zA-Z- &a]+$/.test(interest);
export const isValidPhone = phone => /^[+]?[(]?[0-9]{3}[)]?[-\s.]?[0-9]{3}[-\s.]?[0-9]{4,6}$/im.test(phone);
export const isValidRating = rating => /^\d+$/.test(rating);
export const isValidAddress = address => /^[a-zA-Z0-9\s,.'-]{3,}$/.test(address);
export const isValidZipCode = zip => /(^\d{5}$)|(^\d{5}-\d{4}$)/.test(zip);
export const isValidNumber = num => /^\d+$/.test(num);
export const isValidString = str => /^[a-zA-Z.,:\-_+=|()!;\r\n'"` ]+$/.test(str);
